apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mnlmx55eq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mnlmx55eq-go 
  name: mnlmx55eq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mnlmx55eq-go 
